Ppgz.Web/Areas/Mercaderia/Controllers/GestionProveedoresController.cs
using System;
using System.Web.Mvc;
using Ppgz.Services;
using Ppgz.Web.Infrastructure;
using Ppgz.Web.Infrastructure.Dap;

namespace Ppgz.Web.Areas.Mercaderia.Controllers
{
    [Authorize]
    [TerminosCondiciones]
    public class GestionProveedoresController : Controller
    {
       /* private readonly CommonManager _commonManager = new CommonManager();
        private readonly CuentaManager _cuentaManager = new CuentaManager();
        private readonly ProveedorManager _proveedorManager = new ProveedorManager();
        private readonly MensajesInstitucionalesManager _mensajesInstitucionalesManager = new MensajesInstitucionalesManager();


        [Authorize(Roles = "MAESTRO-MERCADERIA,MERCADERIA-GESTIONPROVEEDORES")]
        public ActionResult Index()
        {
            var cuenta = _commonManager.GetCuentaUsuarioAutenticado();
            var proveedores = _proveedorManager.FindByCuentaId(cuenta.Id);
            var mensajes = _mensajesInstitucionalesManager.FindPublicadosSinLeerByCuentaId(cuenta.Id);
            var cuentaConUsuarioMaestro = _cuentaManager.FindWithUsuarioMaestro(cuenta.Id);

            ViewBag.Proveedores = proveedores;
            ViewBag.Mensajes = mensajes;
            ViewBag.CuentaConUsuarioMaestro = cuentaConUsuarioMaestro;

            return View();
        }

        [Authorize(Roles = "MAESTRO-MERCADERIA,MERCADERIA-GESTIONPROVEEDORES")]
        public JsonResult BuscarProveedor(int id)
        {
            try
            {
                // TODO cambiar en manejador para buscar por proveedor id y cuenta id
                var proveedor = _proveedorManager.Find(id);
                // TODO PASAR MENSAJE AL RESOURCE

                return proveedor == null ? Json(new { error = "Prvoeedor incorrecto" }) : Json(new
                {
                    proveedor.Rfc,
                    Nombre = string.Format
                        ("{0} {1} {2} {3}",
                            proveedor.Nombre1,
                            proveedor.Nombre2,
                            proveedor.Nombre3,
                            proveedor.Nombre4),
                    Teléfono = proveedor.NumeroTelefono,
                    Email = proveedor.Correo,
                    Vendedor = proveedor.VendedorResponsable,
                    proveedor.Region,
                    proveedor.Poblacion,
                    proveedor.Apartado,
                    proveedor.Distrito,
                    proveedor.CodigoPostal,
                    Direccion = proveedor.Calle,
                });
            }
            catch (BusinessException businessEx)
            {
                return Json(new { error = businessEx.Message });
            }
            catch (Exception e)
            {
                var log = CommonManager.BuildMessageLog(
                    TipoMensaje.Error,
                    ControllerContext.Controller.ValueProvider.GetValue("controller").RawValue.ToString(),
                    ControllerContext.Controller.ValueProvider.GetValue("action").RawValue.ToString(),
                    e.ToString(), Request);

                CommonManager.WriteAppLog(log, TipoMensaje.Error);
                return Json(new { error = e.Message });
            }
        }*/
    }
}

Ppgz.Web/Areas/Servicio/Controllers/GestionProveedoresController.cs
using System;
using System.Web.Mvc;
using Ppgz.Services;
using Ppgz.Web.Infrastructure;
using Ppgz.Web.Infrastructure.Dap;

namespace Ppgz.Web.Areas.Servicio.Controllers
{
    [Authorize]
    [TerminosCondiciones]
    public class GestionProveedoresController : Controller
    {
       /* private readonly CommonManager _commonManager = new CommonManager();
        private readonly CuentaManager _cuentaManager = new CuentaManager();
        private readonly ProveedorManager _proveedorManager = new ProveedorManager();
        private readonly MensajesInstitucionalesManager _mensajesInstitucionalesManager = new MensajesInstitucionalesManager();


        [Authorize(Roles = "MAESTRO-SERVICIO,SERVICIO-GESTIONPROVEEDORES")]
        public ActionResult Index()
        {
            var cuenta = _commonManager.GetCuentaUsuarioAutenticado();
            var proveedores = _proveedorManager.FindByCuentaId(cuenta.Id);
            var mensajes = _mensajesInstitucionalesManager.FindPublicadosSinLeerByCuentaId(cuenta.Id);
            var cuentaConUsuarioMaestro = _cuentaManager.FindWithUsuarioMaestro(cuenta.Id);

            ViewBag.Proveedores = proveedores;
            ViewBag.Mensajes = mensajes;
            ViewBag.CuentaConUsuarioMaestro = cuentaConUsuarioMaestro;

            return View();
        }

        [Authorize(Roles = "MAESTRO-SERVICIO,SERVICIO-GESTIONPROVEEDORES")]
        public JsonResult BuscarProveedor(int id)
        {
            try
            {
                // TODO cambiar en manejador para buscar por proveedor id y cuenta id
                var proveedor = _proveedorManager.Find(id);
                // TODO PASAR MENSAJE AL RESOURCE

                return proveedor == null ? Json(new { error = "Prvoeedor incorrecto" }) : Json(new
                {
                    proveedor.Rfc,
                    Nombre = string.Format
                        ("{0} {1} {2} {3}",
                            proveedor.Nombre1,
                            proveedor.Nombre2,
                            proveedor.Nombre3,
                            proveedor.Nombre4),
                    Teléfono = proveedor.NumeroTelefono,
                    Email = proveedor.Correo,
                    Vendedor = proveedor.VendedorResponsable,
                    proveedor.Region,
                    proveedor.Poblacion,
                    proveedor.Apartado,
                    proveedor.Distrito,
                    proveedor.CodigoPostal,
                    Direccion = proveedor.Calle,
                });
            }
            catch (BusinessException businessEx)
            {
                return Json(new { error = businessEx.Message });
            }
            catch (Exception e)
            {
                var log = CommonManager.BuildMessageLog(
                    TipoMensaje.Error,
                    ControllerContext.Controller.ValueProvider.GetValue("controller").RawValue.ToString(),
                    ControllerContext.Controller.ValueProvider.GetValue("action").RawValue.ToString(),
                    e.ToString(), Request);

                CommonManager.WriteAppLog(log, TipoMensaje.Error);
                return Json(new { error = e.Message });
            }
        }
        */
    }
}

Ppgz.Web/Areas/Servicio/Views/GestionProveedores/Index.cshtml
@model dynamic

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var usuarioMaestro = ViewBag.CuentaConUsuarioMaestro.UsuarioMaestro;
    var cuenta = ViewBag.CuentaConUsuarioMaestro.Cuenta;

}

<h2>Gestión de Proveedores</h2>
<p style="border-bottom: solid 1px #eee; color: #888;">
    <i class="fa fa-info" aria-hidden="true"></i> <i>Información de Proveedor</i>
</p>
<div class="col-sm-6">
    <div class="row">
        <div class="col-sm-3"><strong>Nombre</strong></div>
        <div class=" col-sm-9">@cuenta.NombreCuenta</div>
    </div>
    <div class="row">
        <div class="col-sm-3"><strong>Contacto</strong></div>
        <div class=" col-sm-9">
            <p>
                @usuarioMaestro.Nombre @usuarioMaestro.Apellido<i>
                    <br>+@usuarioMaestro.PhoneNumber
                </i><br>@usuarioMaestro.Email
            </p>
        </div>
    </div>
</div>
<div class="col-sm-6">

    <div class="well well2 text-center">
        <i class="fa fa-envelope fa-lg" aria-hidden="true"></i> Tiene @ViewBag.mensajes.Count nuevos mensajes
        <a href="@Url.Action("Index", "MensajesInstitucionales")" class="btn btn-link btn-lg"> Ver Mensajes</a>
    </div>
</div>
<div class="panel panel-default">
    <div class="clearfix"></div>
    <div class="panel-heading">Registros de Razones Sociales</div>
    <div class="panel-body">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-striped table-condensed table-bordered" id="proveedores">
                    <thead>
                        <tr>
                            <th class="text-center">RFC</th>
                            <th class="text-center">Razón Social</th>
                            <th class="text-center"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var proveedor in (ViewBag.Proveedores))
                        {
                            <tr>
                                <td class="text-center vert-align">@(proveedor.Rfc)</td>
                                <td class="text-center vert-align">@proveedor.Nombre1 @proveedor.Nombre2 @proveedor.Nombre3 @proveedor.Nombre4</td>
                                <td class="text-center vert-align">
                                    <div class="btn-group hidden-xs">
                                        <a href="javascript:buscarNumeroProveedor(@proveedor.Id)" class="ver-mensaje"> Ver Detalle</a>
                                    </div>
                                    <div class="btn-group-vertical visible-xs">
                                        <a href="javascript:buscarNumeroProveedor(@proveedor.Id)" class="ver-mensaje"> Ver Detalle</a>
                                    </div>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="buscarModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <strong>Datos del Proveedor</strong>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><span id="mensaje-titulo"></span></h4>
            </div>
            <div class="modal-body">


            </div>

        </div>
    </div>
</div>
<div class="modal fade" id="buscarModalError" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <strong>Error de busquueda del Proveedor</strong>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><span id="mensaje-titulo"></span></h4>
            </div>
            <div class="modal-body">
                <p id="buscarModalError-content"></p>

            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script type="text/javascript">

        var urlBuscarProveedor = "@Url.Action("BuscarProveedor", "GestionProveedores")";

        $(document).ready(function () {
            $('#proveedores').DataTable({
                "language": {
                    "url": "@Url.Content("~/assets/vendor/dataTables-1.10.13/Spanish.json")"
                },
                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Todos"]]
            });
        });



        function buscarNumeroProveedor(id) {



            var data = {
                Id: id
            };

            $.ajax({
                type: "POST",
                url: urlBuscarProveedor,
                data: data,
                cache: false
            }).done(function (result) {

                if (result.error) {

                    $("#buscarModalError-content").text(result.error);
                    $('#buscarModalError').modal('show');
                    return;
                }

                var body = $("#buscarModal .modal-body");

                $(body).html("");

                var dl = $("<dl class='dl-horizontal'></dl>").appendTo(body);

                for (var key in result) {
                    if (result.hasOwnProperty(key)) {
                        if (key.toString() == 'Rfc') {
                            $(dl).append("<dt>" + key.toUpperCase() + "</dt>");
                        } else {
                            $(dl).append("<dt>" + key + "</dt>");
                        }
                        $(dl).append("<dd>" + result[key] + "</dd>");
                    }
                }



                $('#buscarModal').modal('show');


            }).fail(function (response) {
                $('#buscarModal').modal('show');

            });
        }

    </script>
}