Ppgz.Web/Areas/Dap/Controllers/AdministrarEquiposController.cs
using System;
using System.Globalization;
using System.IO;
using System.Web;
using System.Web.Mvc;
using Ppgz.Services;
using Ppgz.Web.Areas.Dap.Models;
using Ppgz.Web.Infrastructure;
using Ppgz.Web.Infrastructure.Dap;
using System.Data;
using System.Linq;
using Ppgz.Repository;


namespace Ppgz.Web.Areas.Dap.Controllers
{
    [Authorize]
    public class AdministrarEquiposController : Controller
    {
        private readonly EquiposManager _equiposManager = new EquiposManager();

        private readonly FallasManager _fallasManager = new FallasManager();

        private readonly ObrasManager _obrasManager = new ObrasManager();

        private readonly ComponentesMecanicosManager _componentesmecanicosManager = new ComponentesMecanicosManager();
        private readonly ComponentesElectricosManager _componentesElectricos_Manager = new ComponentesElectricosManager();

        internal string CargarPdf(HttpPostedFileBase file)
        {
            if (file != null && file.ContentType != "application/pdf")
            {
                //throw new BusinessException(MensajesResource.ERROR_MensajesInstitucionales_PdfInvalido);
            }

            if (file == null)
            {
                // throw new BusinessException(MensajesResource.ERROR_MensajesInstitucionales_PdfInvalido);
            }

            var fileName = Path.GetFileName(file.FileName);

            if (fileName == null)
            {
                //throw new BusinessException(MensajesResource.ERROR_MensajesInstitucionales_PdfInvalido);
            }

            var path = Path.Combine(Server.MapPath("~/Uploads/"), fileName);

            file.SaveAs(path);

            return "~/Uploads/" + fileName;
        }

      
        //asignar los roles para esta funcionalidad
        [Authorize(Roles = "MAESTRO-NAZAN,NAZAN-ADMINISTRAREQUIPOS-CONSULTAR")]

        public ActionResult Index()
        {
            var db = new EntitiesDap();

            var fecha = DateTime.Today.AddMonths(-3);


            ViewBag.obra = db.obras.ToList();

            ViewBag.Equipos = db.equipos.ToList();

            ViewBag.previos = db.previos.ToList();

            ViewBag.componentesmecanicos = db.componentesmecanicos.ToList();

            ViewBag.componenteselectronicos = db.componenteselectricos.ToList();
            ViewBag.ComponentesMecanicosCount = _componentesmecanicosManager.GetSustituciones();
            ViewBag.ComponentesMecanicos = _componentesmecanicosManager.GetSustituciones();
            TempData["sustitucionesmecanicas"] = ViewBag.ComponentesMecanicosCount.Count;
            TempData.Keep();

            ViewBag.ComponentesElectricosCount = _componentesElectricos_Manager.GetSustituciones();
            ViewBag.ComponentesElectricos = _componentesElectricos_Manager.GetSustituciones();
            TempData["sustitucioneselectronicas"] = ViewBag.ComponentesElectricosCount.Count;
            TempData.Keep();

            //ViewBag.EstatusCita = db.estatuscitas.ToList();

            return View();
        }

        public ActionResult Equipos(int id)
        {
            var db = new EntitiesDap();

            TempData["obra_equipo_id"] = id;

            TempData.Keep();

            ViewBag.id = id;

            ViewBag.obra = _obrasManager.Find(id);

            ViewBag.Equipos = _equiposManager.GetEquipos(id);

            ViewBag.previos = db.previos.ToList();

            ViewBag.componentesmecanicos = db.componentesmecanicos.ToList();

            ViewBag.componenteselectronicos = db.componenteselectricos.ToList();

            return View("Index");
        }

        //[Authorize(Roles = "MAESTRO-NAZAN,NAZAN-ADMINISTRARMENSAJESINSTITUCIONALES-LISTAR,NAZAN-ADMINISTRARMENSAJESINSTITUCIONALES-MODIFICAR")]
        //public ActionResult Index()
        //{
        //    ViewBag.mensajes = _mensajesInstitucionalesManager.FindAll();
        //    return View();
        //}
        [Authorize(Roles = "MAESTRO-NAZAN,NAZAN-ADMINISTRAREQUIPOS-CREAR")]
        public ActionResult Crear(int id)
        {
            var obra = _obrasManager.Find(id);

            
            ViewBag.Obras =
             new SelectList(_fallasManager.FindObras(), "id", "nombre", obra.Id);

            return View();
        }
       // [HttpGet]
        public ActionResult Detalle(int id)
        {
            var equipo = _equiposManager.Find(id);

            ViewBag.Obras =
              new SelectList(_equiposManager.FindObras(id), "id", "nombre", equipo.obra_id);

            var db = new EntitiesDap();

            

            ViewBag.ArchivosFotografia = _obrasManager.FindFotografiasEquipos(id);

            ViewBag.ArchivosPlano = _obrasManager.FindPlanosEquipos(id);

            if (equipo == null)
            {
                // TempData["FlashError"] = MensajesResource.ERROR_MensajesInstitucionales_IdIncorrecto;
                return RedirectToAction("Index");
            }

            var equipoModel = new EquipoViewModel()
            {
                Nombre = equipo.Nombre,
                Marca = equipo.Marca,
                Modelo = equipo.Modelo,
                Referencia = equipo.Referencia,
                DimensionesCabina = equipo.DimensionesCabina,
                DimensionesHueco = equipo.DimensionesHueco,
                CargaNominal = equipo.CargaNominal,
                Velocidad = equipo.Velocidad,
                Recorrido = equipo.Recorrido,
                Paradas = equipo.Paradas,
                Accesos = equipo.Accesos,
                VoltajeDeRed = equipo.VoltajeDeRed,
                PotenciaDeMaquina = equipo.PotenciaDeMaquina,
                TipoDeManiobra = equipo.TipoDeManiobra,
                NumeroDeGuayas = equipo.NumeroDeGuayas,
                Fotografia = equipo.Fotografia,
                Plano = equipo.Plano,
                obra_id = equipo.obra_id,
                CantidadPersonas = Convert.ToString(equipo.CantidadPersonas),
                obra = "Obra",
                FechaGarantia = equipo.FechaGarantia.ToString(),
                FechaVencimiento = equipo.FechaVencimiento.ToString()
            };

            return PartialView(equipoModel);
        }

        [Authorize(Roles = "MAESTRO-NAZAN,NAZAN-ADMINISTRAREQUIPOS-MODIFICAR")]
        public ActionResult Editar(int id)
        {
            var equipo = _equiposManager.Find(id);
            TempData["equipo"] = id;
            TempData.Keep();
            var obra = _obrasManager.Find(equipo.obra_id);           

            ViewBag.ObrasEditar =
             new SelectList(_equiposManager.FindObras(), "id", "nombre", obra.Id);
            /*
            ViewBag.Obras2 =
              new SelectList(_obrasManager.FindAll(), "nombre", "nombre", obra.Nombre);

            */

            var db = new EntitiesDap();
            

            ViewBag.ArchivosFotografia = _obrasManager.FindFotografiasEquipos(id);

            ViewBag.ArchivosPlano = _obrasManager.FindPlanosEquipos(id);

            if (equipo == null)
            {
                // TempData["FlashError"] = MensajesResource.ERROR_MensajesInstitucionales_IdIncorrecto;
                return RedirectToAction("Index");
            }

            var equipoModel = new EquipoViewModel()
            {
                Nombre = equipo.Nombre,
                Marca = equipo.Marca,
                Modelo = equipo.Modelo,
                Referencia = equipo.Referencia,
                DimensionesCabina = equipo.DimensionesCabina,
                DimensionesHueco = equipo.DimensionesHueco,
                CargaNominal = equipo.CargaNominal,
                Velocidad = equipo.Velocidad,
                Recorrido = equipo.Recorrido,
                Paradas = equipo.Paradas,
                Accesos = equipo.Accesos,
                VoltajeDeRed = equipo.VoltajeDeRed,
                PotenciaDeMaquina = equipo.PotenciaDeMaquina,
                TipoDeManiobra = equipo.TipoDeManiobra,
                NumeroDeGuayas = equipo.NumeroDeGuayas,
                Fotografia = equipo.Fotografia,
                Plano = equipo.Plano,
                obra_id = equipo.obra_id,
                CantidadPersonas = Convert.ToString(equipo.CantidadPersonas),
                obra = "Obra",
                FechaGarantia = equipo.FechaGarantia.ToString(),
                FechaVencimiento = equipo.FechaVencimiento.ToString()
            };

            return View(equipoModel);
        }
        [Authorize(Roles = "MAESTRO-NAZAN,NAZAN-ADMINISTRAREQUIPOS-MODIFICAR")]
        public ActionResult DetalleEquipo(int id)
        {
            var equipo = _equiposManager.Find(id);

            var obra = _obrasManager.Find(equipo.obra_id);

            ViewBag.ObrasEditar =
             new SelectList(_equiposManager.FindObras(), "id", "nombre", obra.Id);
            /*
            ViewBag.Obras2 =
              new SelectList(_obrasManager.FindAll(), "nombre", "nombre", obra.Nombre);

            */

            var db = new EntitiesDap();


            ViewBag.ArchivosFotografia = _obrasManager.FindFotografiasEquipos(id);

            ViewBag.ArchivosPlano = _obrasManager.FindPlanosEquipos(id);

            if (equipo == null)
            {
                // TempData["FlashError"] = MensajesResource.ERROR_MensajesInstitucionales_IdIncorrecto;
                return RedirectToAction("Index");
            }

            var equipoModel = new EquipoViewModel()
            {
                Nombre = equipo.Nombre,
                Marca = equipo.Marca,
                Modelo = equipo.Modelo,
                Referencia = equipo.Referencia,
                DimensionesCabina = equipo.DimensionesCabina,

Ppgz.Web/Areas/Dap/Views/AdministrarEquipos/Crear.cshtml
@model Ppgz.Web.Areas.Dap.Models.EquipoViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="form-signin-heading">EQUIPOS</h2>
@*<p class="page-description-title"><i class="fa fa-info" aria-hidden="true"></i> <i>Crear Equipo</i></p>*@


<div class="panel panel-default">
    <div class="panel-heading">FORMULARIO DE EQUIPOS</div>
    <div class="panel-body">
        @using (Html.BeginForm("Crear", "AdministrarEquipos", new { ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", @id = "form", role = "form", enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(true)

            <div class="form-group">
                <label for="OBRA" class="col-sm-3 control-label">OBRA</label>
                <div class="col-sm-4">
                    @Html.DropDownListFor(o => o.obra_id, (IEnumerable<SelectListItem>)ViewBag.Obras, "Seleccione un Valor", new { @class = "form-control", @disabled="disabled"})
                    @Html.ValidationMessageFor(o => o.obra_id)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(o => o.Nombre, new { @class = "col-sm-3 control-label" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(o => o.Nombre, new { @class = "form-control" })
                    @Html.ValidationMessageFor(o => o.Nombre)
                </div>
            </div>
                <div class="form-group">
                    @Html.LabelFor(o => o.Marca, new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-4">
                        @Html.TextBoxFor(o => o.Marca, new { @class = "form-control" })
                        @Html.ValidationMessageFor(o => o.Marca)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(o => o.Modelo, new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-4">
                        @Html.TextBoxFor(o => o.Modelo, new { @class = "form-control" })
                        @Html.ValidationMessageFor(o => o.Modelo)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(o => o.Referencia, new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-4">
                        @Html.TextBoxFor(o => o.Referencia, new { @class = "form-control" })
                        @Html.ValidationMessageFor(o => o.Referencia)
                    </div>
                </div>

                <div class="form-group">
                    <label for="DimensionesCabina" class="col-sm-3 control-label">DIMENSIONES&nbsp;DE&nbsp;CABINA</label>
                    <div class="col-sm-4">
                        @Html.TextBoxFor(o => o.DimensionesCabina, new { @class = "form-control" })
                        @Html.ValidationMessageFor(o => o.DimensionesCabina)
                    </div>
                </div>
                <div class="form-group">
                    <label for="DimensionesHueco" class="col-sm-3 control-label">DIMENSIONES&nbsp;DE&nbsp;HUECO</label>
                    <div class="col-sm-4">
                        @Html.TextBoxFor(o => o.DimensionesHueco, new { @class = "form-control" })
                        @Html.ValidationMessageFor(o => o.DimensionesHueco)
                    </div>
                </div>
                <div class="form-group">
                    <label for="CargaNominal" class="col-sm-3 control-label">CARGA&nbsp;NOMINAL</label>
                    <div class="col-sm-4">
                        @Html.TextBoxFor(o => o.CargaNominal, new { @class = "form-control" })
                        @Html.ValidationMessageFor(o => o.CargaNominal)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(o => o.Velocidad, new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-4">
                        @Html.TextBoxFor(o => o.Velocidad, new { @class = "form-control" })
                        @Html.ValidationMessageFor(o => o.Velocidad)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(o => o.Recorrido, new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-4">
                        @Html.TextBoxFor(o => o.Recorrido, new { @class = "form-control" })
                        @Html.ValidationMessageFor(o => o.Recorrido)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(o => o.Paradas, new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-4">
                        @Html.TextBoxFor(o => o.Paradas, new { @class = "form-control" })
                        @Html.ValidationMessageFor(o => o.Paradas)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(o => o.Accesos, new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-4">
                        @Html.TextBoxFor(o => o.Accesos, new { @class = "form-control" })
                        @Html.ValidationMessageFor(o => o.Accesos)
                    </div>
                </div>
                <div class="form-group">
                    <label for="VoltajeDeRed" class="col-sm-3 control-label">VOLTAJE&nbsp;DE&nbsp;RED</label>
                    <div class="col-sm-4">
                        @Html.TextBoxFor(o => o.VoltajeDeRed, new { @class = "form-control" })
                        @Html.ValidationMessageFor(o => o.VoltajeDeRed)
                    </div>
                </div>
                <div class="form-group">
                    <label for="PotenciaDeMaquina" class="col-sm-3 control-label">POTENCIA&nbsp;DE&nbsp;MAQUINA</label>
                    <div class="col-sm-4">
                        @Html.TextBoxFor(o => o.PotenciaDeMaquina, new { @class = "form-control" })
                        @Html.ValidationMessageFor(o => o.PotenciaDeMaquina)
                    </div>
                </div>
                <div class="form-group">
                    <label for="TipoDeManiobra" class="col-sm-3 control-label">TIPO&nbsp;DE&nbsp;MANIOBRA</label>
                    <div class="col-sm-4">
                        @Html.TextBoxFor(o => o.TipoDeManiobra, new { @class = "form-control" })
                        @Html.ValidationMessageFor(o => o.TipoDeManiobra)
                    </div>
                </div>
                <div class="form-group">
                     <label for="NumeroDeGuayas" class="col-sm-3 control-label">NUMERO&nbsp;DE&nbsp;GUAYAS</label>
                    <div class="col-sm-4">
                        @Html.TextBoxFor(o => o.NumeroDeGuayas, new { @class = "form-control" })
                        @Html.ValidationMessageFor(o => o.NumeroDeGuayas)
                    </div>
                </div>
                <div class="form-group">
                    <label for="CantidadPersonas" class="col-sm-3 control-label">CANTIDAD&nbsp;DE&nbsp;PERSONAS</label>
                    <div class="col-sm-4">
                        @Html.TextBoxFor(o => o.CantidadPersonas, new { @class = "form-control" })
                        @Html.ValidationMessageFor(o => o.CantidadPersonas)
                    </div>
                </div>
                <div class="form-group">
                    <label for="FechaGarantia" class="col-sm-3 control-label">FECHA&nbsp;DE&nbsp;GARANTIA</label>
                    <div class="col-sm-4">
                        @Html.TextBoxFor(o => o.FechaGarantia, new { @class = "form-control fecha-hora"})
                        @Html.ValidationMessageFor(o => o.FechaGarantia)
                    </div>
                </div>
                <div class="form-group">
                    <label for="FechaVencimiento" class="col-sm-3 control-label">FECHA&nbsp;DE&nbsp;VENCIMIENTO</label>
                    <div class="col-sm-4">
                        @Html.TextBoxFor(o => o.FechaVencimiento, new { @class = "form-control fecha-hora" })
                        @Html.ValidationMessageFor(o => o.FechaVencimiento)
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">FOTOGRAFIAS</label>
                    <div class="col-sm-4">
                        <div>
                            
                                <ul class="nav nav-tabs" role="tablist" id="text-pdf">

                                    <li role="presentation" id="pdf"><a href="#pdf-panel" aria-controls="pdf-panel" role="tab" data-toggle="tab">CARGAR</a></li>
                                </ul>

                                <div class="tab-content">

                                    <div role="tabpanel" class="tab-pane" id="pdf-panel">
                                        <input type="file" multiple="multiple" style="padding: 20px;" name="Pdf-Fotografia" id="Pdf-Fotografia">
                                        @Html.ValidationMessageFor(k => k.Fotografia)

                                    </div>
                                </div>
                            
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">PLANOS</label>
                    <div class="col-sm-4">
                        <div>
                            
                                <ul class="nav nav-tabs" role="tablist" id="text-pdf">

                                    <li role="presentation" id="pdf"><a href="#pdf-panel1" aria-controls="pdf-panel" role="tab" data-toggle="tab">CARGAR</a></li>
                                </ul>

                                <div class="tab-content">

                                    <div role="tabpanel" class="tab-pane" id="pdf-panel1">
                                        <input type="file" multiple="multiple" style="padding: 20px;" name="Pdf-Plano" id="Pdf-Plano">
                                        @Html.ValidationMessageFor(k => k.Plano)

                                    </div>
                                </div>
                            
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-7">
                        <button type="submit" class="btn btn-primary"><i class="fa fa-floppy-o" aria-hidden="true"></i> GUARDAR</button>
                        <a class="btn btn-default" href="@Url.Action("Index", "AdministrarEquipos")"><i class="fa fa-undo" aria-hidden="true"></i> CANCELAR</a>
                    </div>
                </div>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        
     

        $(document).ready(function () {

            $("#Pdf").bind('change', function () {
        
                if (this.files[0].size / 1024 / 1024 > 3) {
                    $(this).val("");

                    alert('Debe incluir un archivo menor a 3Mb');
                }
            });



            $('.fecha-hora').datetimepicker({
                locale: 'es',

                format: 'DD/MM/YYYY',
                showClose: true,
                sideBySide: true
            });

            $('<input />').attr('type', 'hidden')
                        .attr('name', "Pdf-Plano")
                        .attr('value', "Pdf-Plano")
                        .appendTo('#form');

            $('<input />').attr('type', 'hidden')
                              .attr('name', "Pdf-Fotografia")
                              .attr('value', "Pdf-Fotografia")
                              .appendTo('#form');
        });

    </script>


}

Ppgz.Web/Areas/Dap/Views/AdministrarEquipos/Reporte.cshtml
@model Ppgz.Web.Areas.Dap.Models.EquipoViewModel
@{
    
}
<a style="padding:15px;" class="btn btn-info btn-xs" href="javascript:imprSelecGeneralObra('reportegeneralobra')">
    <i class="fa fa-print" aria-hidden="true"></i> IMPRIMIR
</a>
<div id="reportegeneralobra">
    <div class="modal-header">
        @*<a style="float:right;" href="~/"><img src="@Url.Content("~/assets/img/slogan.png")" class="img-responsive" width="500"></a>*@
        <a class="brand" href="~/"><img src="@Url.Content("~/assets/img/climb-190x64-org.png")" class="img-responsive" width="200"></a>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"><i class="fa fa-times-circle"></i></span>
        </button>
        <h4 class="modal-title">REPORTE DE FALLAS</h4>
    </div>

    <div class="modal-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-8 col-sm-6">
                    <h4 style="color:darkblue;">@Html.DisplayNameFor(o => o.obra)</h4>
                </div>
                <div class="col-4 col-sm-6">
                    @Html.DisplayFor(o => o.obra_id)
                </div>
            </div>
            <div class="row">
                <div class="col-8 col-sm-6">
                    <h4 style="color:darkblue;">@Html.DisplayNameFor(o => o.Nombre)</h4>
                </div>
                <div class="col-4 col-sm-6">
                    @Html.DisplayFor(o => o.Nombre)
                </div>
            </div>
            <div class="row">
                <div class="col-8 col-sm-6">
                    <h4 style="color:darkblue;">@Html.DisplayNameFor(o => o.Marca)</h4>
                </div>
                <div class="col-4 col-sm-6">
                    @Html.DisplayFor(o => o.Marca)
                </div>
            </div>
            <div class="row">
                <div class="col-8 col-sm-6">
                    <h4 style="color:darkblue;">@Html.DisplayNameFor(o => o.Modelo)</h4>
                </div>
                <div class="col-4 col-sm-6">
                    @Html.DisplayFor(o => o.Modelo)
                </div>
            </div>

            <div class="row">
                <div class="col-8 col-sm-6">
                    <h4 style="color:darkblue;">@Html.DisplayNameFor(o => o.Referencia)</h4>
                </div>
                <div class="col-4 col-sm-6">
                    @Html.DisplayFor(o => o.Referencia)
                </div>
            </div>

            <div class="row">
                <div class="col-8 col-sm-6">

                    <h4 style="color:darkblue;">@Html.DisplayNameFor(o => o.DimensionesCabina)</h4>
                </div>
                <div class="col-4 col-sm-6">
                    @Html.DisplayFor(o => o.DimensionesCabina)
                </div>
            </div>
            <div class="row">
                <div class="col-8 col-sm-6">

                    <h4 style="color:darkblue;"> @Html.DisplayNameFor(o => o.DimensionesHueco)</h4>
                </div>
                <div class="col-4 col-sm-6">
                    @Html.DisplayFor(o => o.DimensionesHueco)
                </div>
            </div>
            <div class="row">
                <div class="col-8 col-sm-6">

                    <h4 style="color:darkblue;">@Html.DisplayNameFor(o => o.CargaNominal)</h4>
                </div>
                <div class="col-4 col-sm-6">
                    @Html.DisplayFor(o => o.CargaNominal)
                </div>
            </div>
            <div class="row">
                <div class="col-8 col-sm-6">

                    <h4 style="color:darkblue;">@Html.DisplayNameFor(o => o.Velocidad)</h4>
                </div>
                <div class="col-4 col-sm-6">
                    @Html.DisplayFor(o => o.Velocidad)
                </div>
            </div>
            <div class="row">
                <div class="col-8 col-sm-6">

                    <h4 style="color:darkblue;">@Html.DisplayNameFor(o => o.Recorrido)</h4>
                </div>
                <div class="col-4 col-sm-6">
                    @Html.DisplayFor(o => o.Recorrido)
                </div>
            </div>
            <div class="row">
                <div class="col-8 col-sm-6">

                    <h4 style="color:darkblue;">@Html.DisplayNameFor(o => o.Paradas)</h4>
                </div>
                <div class="col-4 col-sm-6">
                    @Html.DisplayFor(o => o.Paradas)
                </div>
            </div>
            <div class="row">
                <div class="col-8 col-sm-6">

                    <h4 style="color:darkblue;">@Html.DisplayNameFor(o => o.Accesos)</h4>
                </div>
                <div class="col-4 col-sm-6">
                    @Html.DisplayFor(o => o.Accesos)
                </div>
            </div>
            <div class="row">
                <div class="col-8 col-sm-6">

                    <h4 style="color:darkblue;">@Html.DisplayNameFor(o => o.VoltajeDeRed)</h4>
                </div>
                <div class="col-4 col-sm-6">
                    @Html.DisplayFor(o => o.VoltajeDeRed)
                </div>
            </div>
            <div class="row">
                <div class="col-8 col-sm-6">
                    <h4 style="color:darkblue;">@Html.DisplayNameFor(o => o.PotenciaDeMaquina)</h4>
                </div>
                <div class="col-4 col-sm-6">
                    @Html.DisplayFor(o => o.PotenciaDeMaquina)
                </div>
            </div>
            <div class="row">
                <div class="col-8 col-sm-6">
                    <h4 style="color:darkblue;">@Html.DisplayNameFor(o => o.TipoDeManiobra)</h4>
                </div>
                <div class="col-4 col-sm-6">
                    @Html.DisplayFor(o => o.TipoDeManiobra)
                </div>
            </div>
            <div class="row">
                <div class="col-8 col-sm-6">
                    <h4 style="color:darkblue;"> @Html.DisplayNameFor(o => o.NumeroDeGuayas)</h4>
                </div>
                <div class="col-4 col-sm-6">
                    @Html.DisplayFor(o => o.NumeroDeGuayas)
                </div>
            </div>
            <div class="row">
                <div class="col-8 col-sm-6">
                    <h4 style="color:darkblue;"> @Html.DisplayNameFor(o => o.FechaGarantia)</h4>
                </div>
                <div class="col-4 col-sm-6">
                    @Html.DisplayFor(o => o.FechaGarantia)
                </div>
            </div>
            <div class="row">
                <div class="col-8 col-sm-6">
                    <h4 style="color:darkblue;"> @Html.DisplayNameFor(o => o.FechaVencimiento)</h4>
                </div>
                <div class="col-4 col-sm-6">
                    @Html.DisplayFor(o => o.FechaVencimiento)
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">

    </div>
    </div>