Ppgz.Web/Areas/Mercaderia/Controllers/CuentasPagarController.cs
using System;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using ClosedXML.Excel;
using Ppgz.Repository;
using Ppgz.Services;
using Ppgz.Web.Infrastructure;

namespace Ppgz.Web.Areas.Mercaderia.Controllers
{
    [Authorize]
    [TerminosCondiciones]
    public class CuentasPagarController : Controller
    {

      /*  readonly CommonManager _commonManager = new CommonManager();
        readonly ProveedorManager _proveedorManager = new ProveedorManager();

        internal proveedores ProveedorCxp
        {
            get
            {
                if (System.Web.HttpContext.Current.Session["proveedorcxp"] != null)
                {
                    return (proveedores)System.Web.HttpContext.Current.Session["proveedorcxp"];
                }
                return null;
            }
            set
            {
                System.Web.HttpContext.Current.Session["proveedorcxp"] = value;
            }
        }

        // GET: /Mercaderia/CuentasPagar/
        [Authorize(Roles = "MAESTRO-MERCADERIA,MERCADERIA-CUENTASPAGAR")]
        public ActionResult Index()
        {
            var cuenta = _commonManager.GetCuentaUsuarioAutenticado();

            ViewBag.proveedores = _proveedorManager.FindByCuentaId(cuenta.Id);

            return View();
        }

        [Authorize(Roles = "MAESTRO-MERCADERIA,MERCADERIA-CUENTASPAGAR")]
        public ActionResult SeleccionarProveedor(int proveedorId)
        {

            var cuenta = _commonManager.GetCuentaUsuarioAutenticado();

            var proveedor = _proveedorManager.Find(proveedorId, cuenta.Id);

            if (proveedor == null)
            {
                // TODO pasar a recurso
                TempData["FlashError"] = "Proveedor incorrecto";
                return RedirectToAction("Index");
            }

            ProveedorCxp = proveedor;
            return RedirectToAction("Pagos");
        }

        [Authorize(Roles = "MAESTRO-MERCADERIA,MERCADERIA-CUENTASPAGAR")]
        public ActionResult Pagos(string date = null)
        {

            var fecha = DateTime.Today;

            if (!string.IsNullOrWhiteSpace(date))
            {
                fecha = DateTime.ParseExact(date, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            }

            if (ProveedorCxp == null)
            {
                // TODO pasar a recurso
                TempData["FlashError"] = "Proveedor incorrecto";
                return RedirectToAction("Index");
            }

            var partidasManager = new PartidasManager();


            var sociedad = CommonManager.GetConfiguraciones().Single(c => c.Clave == "rfc.common.function.param.bukrs.mercaderia").Valor;
            var dsPagos = partidasManager.GetPagos(ProveedorCxp.NumeroProveedor, sociedad, fecha);

            ViewBag.Pagos = dsPagos.Tables["T_LISTA_PAGOS"];

            ViewBag.Proveedor = ProveedorCxp;

            ViewBag.Fecha = fecha;

            return View();
        }

        [Authorize(Roles = "MAESTRO-MERCADERIA,MERCADERIA-CUENTASPAGAR")]
        public ActionResult PagosDetalle(string numeroDocumento, string date)
        {
            if (ProveedorCxp == null)
            {
                // TODO pasar a recurso
                TempData["FlashError"] = "Proveedor incorrecto";
                return RedirectToAction("Index");
            }

            var fecha = DateTime.ParseExact(date, "dd/MM/yyyy", CultureInfo.InvariantCulture);

            var partidasManager = new PartidasManager();

            var sociedad = CommonManager.GetConfiguraciones().Single(c => c.Clave == "rfc.common.function.param.bukrs.mercaderia").Valor;
            var dsPagos = partidasManager.GetPagos(ProveedorCxp.NumeroProveedor, sociedad, fecha);

            ViewBag.Pago = dsPagos.Tables["T_LISTA_PAGOS"]
                .Select(string.Format("BELNR = '{0}'", numeroDocumento))[0];

            ViewBag.PagoDetalles = dsPagos.Tables["T_PAGOS"]
                .Select(string.Format("BELNR_PAGO = '{0}'", numeroDocumento));

            ViewBag.Proveedor = ProveedorCxp;

            ViewBag.Fecha = fecha;

            return View();
        }

        [Authorize(Roles = "MAESTRO-MERCADERIA,MERCADERIA-CUENTASPAGAR")]
        public void PagoDetallesDescargar(string numeroDocumento, string date)
        {
            if (ProveedorCxp == null)
            {
                return;
            }
            var fecha = DateTime.ParseExact(date, "dd/MM/yyyy", CultureInfo.InvariantCulture);

            var partidasManager = new PartidasManager();

            var sociedad = CommonManager.GetConfiguraciones().Single(c => c.Clave == "rfc.common.function.param.bukrs.mercaderia").Valor;
            var dsPagos = partidasManager.GetPagos(ProveedorCxp.NumeroProveedor, sociedad, fecha);


            var pago = dsPagos.Tables["T_LISTA_PAGOS"]
                .Select(string.Format("BELNR = '{0}'", numeroDocumento))[0];

            var detalles = dsPagos.Tables["T_PAGOS"]
                .Select(string.Format("BELNR_PAGO = '{0}'", numeroDocumento));


            var workbook = new XLWorkbook(Server.MapPath(@"~/App_Data/plantillapagos.xlsx"));
            var ws = workbook.Worksheet(1);

            ws.Cell(3, "B").Value = string.Format("{0} {1} {2} {3}", ProveedorCxp.Nombre1, ProveedorCxp.Nombre2, ProveedorCxp.Nombre3, ProveedorCxp.Nombre4);
            ws.Cell(3, "D").Value = ProveedorCxp.Rfc;
            ws.Cell(5, "B").Value = pago["BELNR"].ToString();
            ws.Cell(6, "B").Value = pago["DMBTR"].ToString();

            var row = 9;

            foreach (var drPago in detalles)
            {
                var tipo = "";
                switch (drPago["BLART_COMPEN"].ToString())
                {
                    case "4":
                        tipo = "Cargo a proveedor";
                        break;
                    case "10":
                        tipo = "Factura a proveedor";
                        break;
                    case "21":
                        tipo = "Factura a proveedor";
                        break;
                    case "23":
                        tipo = "Nota de Cargo";
                        break;
                    case "AB":
                        tipo = "Cargo a proveedor";
                        break;
                    case "DA":
                        tipo = "Cargo a proveedor";
                        break;
                    case "DG":
                        tipo = "Cargo a proveedor";
                        break;
                    case "DZ":
                        tipo = "Pago de proveedor";
                        break;
                    case "KA":
                        tipo = "Cargo a proveedor";
                        break;
                    case "KG":
                        tipo = "Cargo a proveedor";
                        break;
                    case "KR":
                        tipo = "Devolución";
                        break;
                    case "":
                        tipo = "Cargo a proveedor";
                        break;
                    case "RE":

                        if ((decimal)drPago["DMBTR_COMPEN"] > 0)
                        {
                            tipo = "Factura de mercancia";
                            break;

                        }
                        tipo = "Devolucion de mercancia";
                        break;

                    case "RV":
                        tipo = "Cargo a proveedor";
                        break;
                    case "SA":
                        tipo = "Cargo a proveedor";
                        break;
                    case "ZN":
                        tipo = "Anulación de documento";
                        break;
                    case "ZP":
                        tipo = "Pago";
                        break;
                }

                ws.Cell(row, "A").Value = drPago["XBLNR"].ToString();
                ws.Cell(row, "B").Value =  drPago["DMBTR_COMPEN"].ToString();
                ws.Cell(row, "C").Value = drPago["WAERS_COMPEN"].ToString();
                ws.Cell(row, "D").Value = tipo;

                row++;

            }

            FileManager.ExportExcel(workbook, "PAG_" + pago["BELNR"], HttpContext);
        }

        [Authorize(Roles = "MAESTRO-MERCADERIA,MERCADERIA-CUENTASPAGAR")]
        public ActionResult Devoluciones(string numeroDocumento, string date = null)
        {
            var fecha = DateTime.Today;

            if (!string.IsNullOrWhiteSpace(date))
            {
                fecha = DateTime.ParseExact(date, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            }

            if (ProveedorCxp == null)
            {
                // TODO pasar a recurso
                TempData["FlashError"] = "Proveedor incorrecto";
                return RedirectToAction("Index");
            }

            var partidasManager = new PartidasManager();

            var sociedad = CommonManager.GetConfiguraciones().Single(c => c.Clave == "rfc.common.function.param.bukrs.mercaderia").Valor;
            var dsDevoluciones = partidasManager.GetDevoluciones(ProveedorCxp.NumeroProveedor, sociedad, fecha);

            ViewBag.Devoluciones = dsDevoluciones.Tables["T_DEVOLUCIONES"];

            ViewBag.Proveedor = ProveedorCxp;
            ViewBag.Fecha = fecha;
            return View();
        }

        [Authorize(Roles = "MAESTRO-MERCADERIA,MERCADERIA-CUENTASPAGAR")]
        public ActionResult DevolucionesDetalle(string numeroDocumento, string date)
        {
            if (ProveedorCxp == null)
            {
                // TODO pasar a recurso
                TempData["FlashError"] = "Proveedor incorrecto";
                return RedirectToAction("Index");
            }
            var fecha = DateTime.ParseExact(date, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            var partidasManager = new PartidasManager();

Ppgz.Web/Areas/Servicio/Views/CuentasPagar/Devoluciones.cshtml
@using System.Data
@using System.Globalization
@using Ppgz.Repository
@{
    ViewBag.Title = "Devoluciones";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var dtDevoluciones = (DataTable)ViewBag.Devoluciones;

    var proveedor = (proveedore)ViewBag.Proveedor;
    var fechaParam = (DateTime)ViewBag.Fecha;
}

<h2>Devoluciones</h2>
<p class="page-description-title">
    <i class="fa fa-calculator" aria-hidden="true"></i> 
    <i>Devoluciones registradas</i>
</p>

<div class="panel panel-default">
    <div class="panel-heading">Proveedor Seleccionado</div>
    <div class="panel-body">
        <div class="row">
            <label class="col-sm-2 control-label">RFC</label>
            <div class="col-sm-3">
                <div>@proveedor.Rfc</div>
            </div>
            <label class="col-sm-2 control-label">Nombre</label>
            <div class="col-sm-3">
                <div>@proveedor.Nombre1</div>
            </div>
            <div class="col-sm-2">
                <a href="@Url.Action("Index", "CuentasPagar")" class="btn btn-warning btn-xs"> <i class="fa fa-refresh" aria-hidden="true"></i>  Cambiar</a>
            </div>
        </div>

    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">Devoluciones</div>
    <div class="panel-body">
        <div class="col-md-12">
            <div class="row" style="display: none;">
                <label class="col-sm-2">Fecha</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="fecha" id="fecha" placeholder="Fecha" />
                </div>
            </div>
            <table id="devoluciones" class="table table-striped table-condensed table-bordered">
                <thead>
                <tr>
                    <th class="text-center">Folio de referencia</th>
                    <th class="text-center">Fecha</th>
                    <th class="text-center">Importe</th>
                    <th class="text-center"></th>
                </tr>
                </thead>
                <tbody>
                @foreach (DataRow devolucion in dtDevoluciones.Rows)
                {

                    var fecha = DateTime.ParseExact(
                        devolucion["BLDAT"].ToString(),
                        "yyyyMMdd",
                        CultureInfo.InvariantCulture);

                    <tr>
                        <td class="text-center vert-align">@devolucion["XBLNR"]</td>
                        <td class="text-center vert-align">@fecha.ToString("dd/MM/yyyy")</td>
                        <td class="text-right vert-align">@string.Format("{0:N}", devolucion["DMBTR"])</td>
                        <td class="text-center vert-align">
                            <a class="btn btn-primary btn-xs" href="@Url.Action("DevolucionesDetalle", "CuentasPagar", new { @numeroDocumento = @devolucion["BELNR"], date = fechaParam.ToString("dd/MM/yyyy") })">
                                Ver Detalle
                            </a>
                        </td>
                    </tr>
                }
                </tbody>

            </table>
        </div>
    </div>
</div>
@section Scripts {
    <script type="text/javascript">      
        $(document).ready(function () {
            $('#devoluciones').DataTable({
                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/1.10.13/i18n/Spanish.json"
                },
                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Todos"]]
            });

            $('#fecha').datetimepicker({
                locale: 'es',
                format: 'DD/MM/YYYY',
                defaultDate: "@fechaParam.ToString("yyyy/MM/dd")"
            });

            $("#fecha").on("dp.change", function () {
                location.href = "@Url.Action("Devoluciones", "CuentasPagar")" + "?date=" + $(this).val();
            });
        });
    </script>
}

Ppgz.Web/Areas/Servicio/Views/CuentasPagar/DevolucionesDetalle.cshtml
@using System.Data
@using System.Globalization
@using Ppgz.Repository
@{
    ViewBag.Title = "Detalle de Devoluciones";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var drDevolucion = (DataRow)ViewBag.Devolucion;


    var fechaDevolucion = DateTime.ParseExact(
                        drDevolucion["BLDAT"].ToString(),
                        "yyyyMMdd",
                        CultureInfo.InvariantCulture);
    

    var drDevolucionDetalles = (DataRow[])ViewBag.DevolucionDetalles;

    var proveedor = (proveedore)ViewBag.Proveedor;

    var subTotal = drDevolucionDetalles.Aggregate<DataRow, decimal>(0, (current, dr) => current + decimal.Parse(dr["DMBTR"].ToString()));

    decimal impuesto = ViewBag.Impuesto;

    var total = decimal.Parse(@ViewBag.devolucion["DMBTR"].ToString()) * -1;

    var cantidadTotal = drDevolucionDetalles.Aggregate<DataRow, decimal>(0, (current, dr) => current + decimal.Parse(dr["MENGE"].ToString()));
    
    var fechaParam = (DateTime)ViewBag.Fecha;
}

<h2>Gestión de Devoluciones</h2>
<p class="page-description-title">
    <i class="fa fa-calculator" aria-hidden="true"></i>
    <i>Detalles de la devolución</i>
</p>
<a class="btn btn-link" href="@Url.Action("Devoluciones", "CuentasPagar", new { date = fechaParam.ToString("dd/MM/yyyy") })"> <i class="fa fa-arrow-left" aria-hidden="true"></i> Ver otra devolución</a>
<div class="panel panel-default">
    <div class="panel-heading">Proveedor Seleccionado</div>
    <div class="panel-body">
        <div class="row">
            <label class="col-sm-2 control-label">RFC</label>
            <div class="col-sm-3">
                <div>@proveedor.Rfc</div>
            </div>
            <label class="col-sm-2 control-label">Nombre</label>
            <div class="col-sm-3">
                <div>@proveedor.Nombre1</div>
            </div>
            <div class="col-sm-2">
                <a href="@Url.Action("Index", "CuentasPagar")" class="btn btn-warning btn-xs"> <i class="fa fa-refresh" aria-hidden="true"></i> Cambiar</a>
            </div>
        </div>

    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">Gestión de Devolución</div>
    <div class="panel-body">
        <div class="col-md-12">
            <div class="row">
                <div class="col-sm-6">
                    <div class="clearfix">
                        <dl class="dl-horizontal">
                            <dt>Folio de Referencia: </dt>
                            <dd class="text-right">@drDevolucion["XBLNR"]</dd>
                            <dt>Fecha: </dt>
                            <dd class="text-right">@fechaDevolucion.ToString("dd/MM/yyyy")</dd>
                            <dt>Total Pares Devueltos: </dt>
                            <dd class="text-right">@string.Format("{0:N}", @cantidadTotal)</dd>
                            <dt>Sub Total: </dt>
                            <dd class="text-right">@string.Format("{0:N}", @subTotal)</dd>
                            <dt>IVA: </dt>
                            <dd class="text-right">@string.Format("{0:N}", @impuesto)</dd>
                            <dt>Total: </dt>
                            <dd class="text-right">@string.Format("{0:N}", @total)</dd>
                        </dl>
                    </div>

                </div>
                <div class="col-sm-6 text-right">
                    <a href="@Url.Action("DevolucionesDetalleDescargar", "CuentasPagar", new {@numeroDocumento = @drDevolucion["BELNR"], date = fechaParam.ToString("dd/MM/yyyy")})" class="btn btn-primary"><i class="fa fa-download" aria-hidden="true"></i> Descargar</a>
                </div>
            </div>
            <hr style="margin-top: 0;"/>
            <table id="devolucionesDetalle" class="table table-striped table-condensed table-bordered">
                <thead>
                <tr>
                    <th class="text-center">Artículo</th>
                    <th class="text-center">Descripción</th>
                    <th class="text-center">Total</th>
                    <th class="text-center">Cantidad</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var detalle in drDevolucionDetalles)
                {
                    <tr>

                        <td class="text-center">@detalle["MATNR"]</td>
                        <td class="text-center">@detalle["MAKTX"]</td>
                        <td class="text-right">@string.Format("{0:N}", detalle["DMBTR"])</td>
                        <td class="text-center">@detalle["MENGE"]</td>
                    </tr>
                }
                </tbody>
            </table>
            <hr/>
            <div class="clearfix">
                <dl class="dl-horizontal pull-right">
                    <dt>Total Pares Devueltos: </dt>
                    <dd class="text-right">@string.Format("{0:N}", @cantidadTotal)</dd>
                    <dt>Sub Total: </dt>
                    <dd class="text-right">@string.Format("{0:N}", @subTotal)</dd>
                    <dt>IVA: </dt>
                    <dd class="text-right">@string.Format("{0:N}", @impuesto)</dd>
                    <dt>Total: </dt>
                    <dd class="text-right">@string.Format("{0:N}", @total)</dd>
                </dl>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        var usuarioMensajes = "@ViewBag.mensajesUsuario";

        $(document).ready(function () {



            $('#devolucionesDetalle').DataTable({
                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/1.10.13/i18n/Spanish.json"
                },
                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Todos"]]
            });
        });


    </script>
}

Ppgz.Web/Areas/Servicio/Views/CuentasPagar/Index.cshtml
@{
    ViewBag.Title = "Cuentas por Pagar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="form-signin-heading">Cuentas por Pagar</h2>
<p class="page-description-title"><i class="fa fa-calculator" aria-hidden="true"></i> <i>Seleccione una Razón Social.</i></p>

<div class="panel panel-default">
    <div class="panel-heading">Razones Sociales</div>
    <div class="panel-body">
        <div class="col-md-12">
            <table id="cuentasXpagar" class="table table-striped table-condensed table-bordered">
                <thead>
                    <tr>
                        <th class="text-center">Número Proveedor</th>
                        <th class="text-center">RFC</th>
                        <th class="text-center">Razón Social</th>
                        <th class="text-center"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var proveedor in (ViewBag.proveedores))
                    {
                        <tr>
                            <td class="text-center">@proveedor.NumeroProveedor</td>
                            <td class="text-center">@proveedor.Rfc</td>
                            <td class="text-center vert-align">@proveedor.Nombre1 @proveedor.Nombre2 @proveedor.Nombre3 @proveedor.Nombre4</td>
                            <td class="text-center">
                                @*<a id="btnProveedor" data-idproveedor="@proveedor.Id" href="#"><i class="fa fa-check" aria-hidden="true"></i> Ver Detalle</a>*@

                                <a class="btn btn-primary btn-sm" href="@Url.Action("SeleccionarProveedor", "CuentasPagar", new { @proveedorId = @proveedor.Id })">
                                    <i class="fa fa-check" aria-hidden="true"></i> Seleccionar
                                </a>

                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
@section Scripts {
    <script type="text/javascript">



        $(document).ready(function () {

            $("#navbar > ul > li.dropdown.active > ul").hide();

            $('#cuentasXpagar').DataTable({
                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/1.10.13/i18n/Spanish.json"
                },
                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Todos"]]
            });
        });


    </script>
}

Ppgz.Web/Areas/Servicio/Views/CuentasPagar/Pagos.cshtml
@using System.Data
@using System.Globalization
@using Ppgz.Repository
@{
    ViewBag.Title = "Gestión de Pagos";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var pagos = (DataTable)ViewBag.Pagos;
    var proveedor = (proveedore)ViewBag.Proveedor;
    var fechaParam =(DateTime)ViewBag.Fecha;
}

<h2>Gestión de Pagos</h2>
<p class="page-description-title">
    <i class="fa fa-calculator" aria-hidden="true"></i> 
    <i>En esta sección podrán gestionar los pagos que tiene del Grupo Nazan.</i>
</p>
<div class="panel panel-default">
    <div class="panel-heading">Proveedor Seleccionado</div>
    <div class="panel-body">
        <div class="row">
            <label class="col-sm-2 control-label">RFC</label>
            <div class="col-sm-3">
                <div>@proveedor.Rfc</div>
            </div>
            <label class="col-sm-2 control-label">Nombre</label>
            <div class="col-sm-3">
                <div>@proveedor.Nombre1</div>
            </div>
            <div class="col-sm-2">
                <a href="@Url.Action("Index", "CuentasPagar")" class="btn btn-warning btn-xs"> <i class="fa fa-refresh" aria-hidden="true"></i>  Cambiar</a>
            </div>
        </div>

    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">Pagos</div>
    <div class="panel-body">
        <div class="col-md-12">
            <div class="row">
                <label class="col-sm-2">Fecha</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="fecha" id="fecha" placeholder="Fecha" />
                </div>
            </div>
            <table id="pagos" class="table table-striped table-condensed table-bordered">
                <thead>
                <tr>
                    <th class="text-center">Referencia de pago</th>
                    <th class="text-center">Fecha de Pago</th>
                    <th class="text-center">Importe</th>
                    <th class="text-center"></th>

                </tr>
                </thead>
                <tbody>
                @foreach (DataRow pago in pagos.Rows)
                {
                    var fecha = DateTime.ParseExact(
                        pago["FECHA_PAGO"].ToString(),
                        "yyyyMMdd",
                        CultureInfo.InvariantCulture);
                    <tr>
                        <td class="text-center vert-align">@pago["BELNR"]</td>
                        <td class="text-center vert-align">@fecha.ToString("dd/MM/yyyy")</td>
                        <td class="text-right vert-align">@string.Format("{0:N}", pago["DMBTR"])</td>
                        <td class="text-center vert-align">
                            <a class="btn btn-primary btn-xs" href="@Url.Action("PagosDetalle", "CuentasPagar", new { @numeroDocumento = @pago["BELNR"], date = fechaParam.ToString("dd/MM/yyyy") })">
                                Ver Detalle
                            </a>
                        </td>

                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts {

    <script type="text/javascript">

    $(document).ready(function () {
        $('#pagos').DataTable({
            "language": {
                "url": "https://cdn.datatables.net/plug-ins/1.10.13/i18n/Spanish.json"
            },
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Todos"]]
        });

        $('#fecha').datetimepicker({
            locale: 'es',
            format: 'DD/MM/YYYY',
            defaultDate: "@fechaParam.ToString("yyyy/MM/dd")"
        });

        $("#fecha").on("dp.change", function () {
            location.href = "@Url.Action("Pagos", "CuentasPagar")" + "?date=" + $(this).val();
        });
    });
    </script>
   
}

Ppgz.Web/Areas/Servicio/Views/CuentasPagar/PagosPendientes.cshtml
@using System.Data
@using Ppgz.Repository
@{
    ViewBag.Title = "Gestión de Pagos";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var pagosPendientes = (DataTable)ViewBag.PagosPendientes;
    var proveedor = (proveedore)ViewBag.Proveedor;
    var importeTotal = pagosPendientes.Rows.Cast<DataRow>()
        .Aggregate<DataRow, decimal>(0, (current, pagoPendiente) => current + decimal.Parse(pagoPendiente["DMBTR"].ToString()));
}

<h2>Gestión de Pagos Pendientes</h2>
<p class="page-description-title"><i class="fa fa-calculator" aria-hidden="true"></i>
    <i>En esta sección podrán gestionar los pagos pendientes</i>
</p>

<div class="panel panel-default">
    <div class="panel-heading">Proveedor Seleccionado</div>
    <div class="panel-body">
        <div class="row">
            <label class="col-sm-2 control-label">RFC</label>
            <div class="col-sm-3">
                <div>@proveedor.Rfc</div>
            </div>
            <label class="col-sm-2 control-label">Nombre</label>
            <div class="col-sm-3">
                <div>@proveedor.Nombre1</div>
            </div>
            <div class="col-sm-2">
                <a href="@Url.Action("Index", "CuentasPagar")" class="btn btn-warning btn-xs"> <i class="fa fa-refresh" aria-hidden="true"></i>  Cambiar</a>
            </div>
        </div>

    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">Pagos Pendientes</div>
    <div class="panel-body">
        <div class="col-md-12">
            <table id="" class="table table-striped table-condensed table-bordered">
                <thead>
                    <tr>
                        <th class="text-center">Fecha</th>
                        <th class="text-center">Proveedor RFC</th>
                        <th class="text-center">Proveedor Razón Social</th>
                        <th class="text-center">Importe</th>
                        <th class="text-center">Detalle</th>
                    </tr>
                </thead>
                <tbody>

                    <tr>
                        <td class="text-center">@DateTime.Today.ToString("dd/MM/yyyy")</td>
                        <td class="text-center">@proveedor.Rfc</td>
                        <td class="text-center">@proveedor.Nombre1</td>
                        <td class="text-right">@string.Format("{0:N}", importeTotal)</td>
                        <td class="text-center">
                            <a class="btn btn-primary btn-xs" href="@Url.Action("PagosPendientesDetalle", "CuentasPagar", new { proveedorId = ViewBag.proveedor.Id })">Detalle</a>
                        </td>
                    </tr>

                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#pagosPendiente').DataTable({
                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/1.10.13/i18n/Spanish.json"
                },
                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Todos"]]
            });
        });
    </script>
}