Ppgz.Web/Areas/Mercaderia/Controllers/ReporteProveedoresController.cs
using System;
using System.Data;
using System.Web.Mvc;
using Ppgz.Services;
using Ppgz.Web.Infrastructure;

namespace Ppgz.Web.Areas.Mercaderia.Controllers
{
    [Authorize]
    [TerminosCondiciones]
    public class ReporteProveedoresController : Controller
    {
      /*
        private readonly CommonManager _commonManager = new CommonManager();
        readonly ProveedorManager _proveedorManager = new ProveedorManager();
        readonly ReporteProveedorManager _reporteProveedorManager = new ReporteProveedorManager();
        //
        // GET: /Mercaderia/ReporteProveedores/
        [Authorize(Roles = "MAESTRO-MERCADERIA,MERCADERIA-REPORTESPROVEEDORES")]
        public ActionResult Index()
        {
 
            var cuenta = _commonManager.GetCuentaUsuarioAutenticado();

            ViewBag.proveedores = _proveedorManager.FindByCuentaId(cuenta.Id);

           

            return View();
        }

        [Authorize(Roles = "MAESTRO-MERCADERIA,MERCADERIA-REPORTESPROVEEDORES")]
        public ActionResult Reportes(int proveedorId = 0)
        {
            int id = proveedorId > 0 ? proveedorId : Convert.ToInt32(System.Web.HttpContext.Current.Session["proveedorId"]);

            if (id == 0)
                return RedirectToAction("Index");

            var proveedor = _proveedorManager.Find(id);
            ViewBag.proveedor = proveedor;
            try
            {
                ViewBag.reportes = _reporteProveedorManager.FindReporteProveedor(proveedor.NumeroProveedor);

                ViewBag.nivelservicio = _reporteProveedorManager.FindNivelSerNiveleseervicio(proveedor.Id);

            }
            catch (Exception ex)
            {
                if (ex.Message == "NOT_DATA_FOUND")
                {
                    TempData["FlashError"] = "No hay datos para este proveedor"; 
                    return RedirectToAction("Index");
                }


                throw;
            }

            return View();
        }

        [Authorize(Roles = "MAESTRO-MERCADERIA,MERCADERIA-REPORTESPROVEEDORES")]
        public void Descargar(string numeroProveedor)
        {
            var detalles = _reporteProveedorManager.FindReporteProveedor(numeroProveedor);

            var proveedor = _proveedorManager.FindByNumeroProveedor(numeroProveedor);
            

            var dt = new DataTable();
            dt.Columns.Add("Id Proveedor");
            dt.Columns.Add("Nombre Proveedor");
            dt.Columns.Add("Material");
            dt.Columns.Add("Nombre Material");
            dt.Columns.Add("Fecha Proceso");
            dt.Columns.Add("Unidad de Medida");
            dt.Columns.Add("Ventas Actual - 2 meses");
            dt.Columns.Add("Ventas Actual - 1 meses");
            dt.Columns.Add("Ventas Actual");
            dt.Columns.Add("Total Ventas");
            dt.Columns.Add("Cálculo Total");
            dt.Columns.Add("Inventario TDA");
            dt.Columns.Add("Inventario Tránsito");
            dt.Columns.Add("Inventario CEDIS");
            dt.Columns.Add("Pedidos Pendientes(TDA + CEDIS)");
            dt.Columns.Add("Estatus Material");


            foreach (var detalle in detalles)
            {
                dt.Rows.Add(
                    detalle.NumeroProveedor,
                    detalle.NombreProveedor,
                    detalle.Material,
                    detalle.NombreMaterial,
                    detalle.FechaProceso.ToString("dd/MM/yyyy"),
                    detalle.UnidadMedida,
                    detalle.CantidadVentas2,
                    detalle.CantidadVentas1,
                    detalle.CantidadVentas,
                    detalle.CantidadTotal,
                    detalle.CalculoTotal,
                    detalle.InvTienda,
                    detalle.InvTransito,
                    detalle.InvCedis,
                    detalle.PedidosPendiente,
                    detalle.EstadoMaterial);

            }

            FileManager.ExportExcel(dt,proveedor.NumeroProveedor, HttpContext);
        }
        */
    }
}

Ppgz.Web/Areas/Servicio/Controllers/ReporteProveedoresController.cs
using System;
using System.Data;
using System.Web.Mvc;
using Ppgz.Services;
using Ppgz.Web.Infrastructure;

namespace Ppgz.Web.Areas.Servicio.Controllers
{
    [Authorize]
    [TerminosCondiciones]
    public class ReporteProveedoresController : Controller
    {
      /*
        private readonly CommonManager _commonManager = new CommonManager();
        readonly ProveedorManager _proveedorManager = new ProveedorManager();
        readonly ReporteProveedorManager _reporteProveedorManager = new ReporteProveedorManager();

        [Authorize(Roles = "MAESTRO-SERVICIO,SERVICIO-REPORTESPROVEEDORES")]
        public ActionResult Index()
        {
 
            var cuenta = _commonManager.GetCuentaUsuarioAutenticado();

            ViewBag.proveedores = _proveedorManager.FindByCuentaId(cuenta.Id);

           

            return View();
        }

        [Authorize(Roles = "MAESTRO-SERVICIO,SERVICIO-REPORTESPROVEEDORES")]
        public ActionResult Reportes(int proveedorId = 0)
        {
            int id = proveedorId > 0 ? proveedorId : Convert.ToInt32(System.Web.HttpContext.Current.Session["proveedorId"]);

            if (id == 0)
                return RedirectToAction("Index");

            ViewBag.proveedor = _proveedorManager.Find(id);
            try
            {
                ViewBag.reportes = _reporteProveedorManager.FindReporteProveedor(ViewBag.proveedor.NumeroProveedor);

                ViewBag.nivelservicio = _reporteProveedorManager.FindNivelSerNiveleseervicio(ViewBag.proveedor.NumeroProveedor);

            }
            catch (Exception ex)
            {
                if (ex.Message == "NOT_DATA_FOUND")
                {
                    TempData["FlashError"] = "No hay datos para este proveedor"; 
                    return RedirectToAction("Index");
                }


                throw;
            }

            return View();
        }

        [Authorize(Roles = "MAESTRO-SERVICIO,SERVICIO-REPORTESPROVEEDORES")]
        public void Descargar(string numeroProveedor)
        {
            var detalles = _reporteProveedorManager.FindReporteProveedor(numeroProveedor);

            var proveedor = _proveedorManager.FindByNumeroProveedor(numeroProveedor);
            

            var dt = new DataTable();
            dt.Columns.Add("Id Proveedor");
            dt.Columns.Add("Nombre Proveedor");
            dt.Columns.Add("Material");
            dt.Columns.Add("Nombre Material");
            dt.Columns.Add("Fecha Proceso");
            dt.Columns.Add("Unidad de Medida");
            dt.Columns.Add("Ventas Actual - 2 meses");
            dt.Columns.Add("Ventas Actual - 1 meses");
            dt.Columns.Add("Ventas Actual");
            dt.Columns.Add("Total Ventas");
            dt.Columns.Add("Cálculo Total");
            dt.Columns.Add("Inventario TDA");
            dt.Columns.Add("Inventario Tránsito");
            dt.Columns.Add("Inventario CEDIS");
            dt.Columns.Add("Pedidos Pendientes(TDA + CEDIS)");
            dt.Columns.Add("Estatus Material");


            foreach (var detalle in detalles)
            {
                dt.Rows.Add(
                    detalle.NumeroProveedor,
                    detalle.NombreProveedor,
                    detalle.Material,
                    detalle.NombreMaterial,
                    detalle.FechaProceso.ToString("dd/MM/yyyy"),
                    detalle.UnidadMedida,
                    detalle.CantidadVentas2,
                    detalle.CantidadVentas1,
                    detalle.CantidadVentas,
                    detalle.CantidadTotal,
                    detalle.CalculoTotal,
                    detalle.InvTienda,
                    detalle.InvTransito,
                    detalle.InvCedis,
                    detalle.PedidosPendiente,
                    detalle.EstadoMaterial);

            }

            FileManager.ExportExcel(dt,proveedor.NumeroProveedor, HttpContext);
        }
        */
    }
}

Ppgz.Web/Areas/Servicio/Views/ReporteProveedores/Index.cshtml
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Reporte Proveedores";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="form-signin-heading">Reporte Proveedores</h2>
<p class="page-description-title"><i class="fa fa-calculator" aria-hidden="true"></i> <i>Seleccione una Razón Social.</i></p>

<div class="panel panel-default">
    <div class="panel-heading">Razones Sociales</div>
    <div class="panel-body">
        <div class="col-md-12">
            <table id="reporteProveedor" class="table table-striped table-condensed table-bordered">
                <thead>
                    <tr>
                        <th class="text-center">Número Proveedor</th>
                        <th class="text-center">Nombre</th>
                        <th class="text-center"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var proveedor in (ViewBag.proveedores))
                    {
                        <tr>
                            <td class="text-center">@proveedor.NumeroProveedor</td>
                            <td class="text-center vert-align">@proveedor.Nombre1</td>
                            <td class="text-center">
                                <a class="button btn-primary btn-sm" href="@Url.Action("Reportes", "ReporteProveedores", new { proveedorId = proveedor.Id })">
                                    <i class="fa fa-check" aria-hidden="true"></i> Seleccionar
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
@section Scripts {
    <script type="text/javascript">

        var proveedorId = "@ViewBag.proveedorId";

        $(document).ready(function () {

            if (proveedorId === "") {
                $("#navbar > ul:nth-child(1) > li:nth-child(2)").css("display", "none");
            }
            $(document).on("click", "#btnProveedor", function () {
                fnProveedorSeleccionado($(this).data('idproveedor'));
            });
            $('#reporteProveedor').DataTable({
                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/1.10.13/i18n/Spanish.json"
                },
                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Todos"]]
            });
        });
    </script>
}

Ppgz.Web/Areas/Servicio/Views/ReporteProveedores/Reportes.cshtml
@using System.Globalization
@using Microsoft.AspNet.Identity
@using Ppgz.Repository
@{
    ViewBag.Title = "Reportes Proveedores";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var proveedor = (proveedore)ViewBag.Proveedor;
}

<h2>Reportes Proveedores - Grupo Nazan</h2>
<p class="page-description-title">
    <i class="fa fa-info" aria-hidden="true"></i>
    <i>En esta sección podrán gestionar los reportes que tiene con el Grupo Nazan. </i>
</p>
<div class="panel panel-default">
    <div class="panel-heading">Proveedor Seleccionado</div>
    <div class="panel-body">
        <div class="row">
            <label class="col-sm-2 control-label">RFC</label>
            <div class="col-sm-3">
                <div>@proveedor.Rfc</div>
            </div>
            <label class="col-sm-2 control-label">Nombre</label>
            <div class="col-sm-3">
                <div>@proveedor.Nombre1</div>
            </div>
            <div class="col-sm-2">
                <a href="@Url.Action("Index", "CuentasPagar")" class="btn btn-warning btn-xs"> <i class="fa fa-refresh" aria-hidden="true"></i>  Cambiar</a>
            </div>
        </div>

    </div>
</div>
<div class="panel panel-default">
    
    @if (ViewBag.nivelservicio != null)
    {
        <div class="panel-heading">Nivel de servicio</div>
        <div class="col-sm-4">
            Ultimo Mes : <strong>@ViewBag.nivelservicio.UltimoMes %</strong><br/>
            Temporada Actual: <strong>@ViewBag.nivelservicio.TemporadaActual %</strong><br/>
            Temporada Anual : <strong>@ViewBag.nivelservicio.AcumuladoAnual %</strong><br/>
        </div>
        <div class="col-sm-5">
            Pedido Atrasado : <strong>@ViewBag.nivelservicio.PedidoAtrasado</strong><br/>
            Pedido en Tiempo: <strong>@ViewBag.nivelservicio.PedidoEnTiempo</strong><br/>
            Pedido Total: <strong>@ViewBag.nivelservicio.PedidoTotal</strong><br/>
        </div>
        <hr/>
    }

    <div class="col-sm-12">
        <a href="@Url.Action("Descargar", "ReporteProveedores", new {@numeroProveedor = ViewBag.proveedor.NumeroProveedor})" style="margin-top: 5px; margin-bottom: 5px;" class="btn btn-primary"><i class="fa fa-download" aria-hidden="true"></i> Descargar</a>
    </div>
    <div class="clearfix"></div>
    <div class="panel-heading">Reporte</div>
    <div class="panel-body">
        <div class="table-responsive">
            <table id="reporteDetalle" class="table table-striped table-condensed table-bordered">
                <thead>
                <tr>
                    <th class="text-center">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspId_Proveedor&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</th>
                    <th class="text-center">Nombre_Proveedor</th>
                    <th class="text-center">Material</th>
                    <th class="text-center">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Nombre_Material&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</th>
                    <th class="text-center">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspFecha_Proceso&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</th>
                    <th class="text-center">Unidad de Medida</th>
                    <th class="text-center">Ventas Actual - 2 meses</th>
                    <th class="text-center">Ventas Actual - 1 meses</th>
                    <th class="text-center">Ventas Actual</th>
                    <th class="text-center">Total Ventas</th>
                    <th class="text-center">Cálculo Total</th>
                    <th class="text-center">Inventario TDA</th>
                    <th class="text-center">Inventario Tránsito</th>
                    <th class="text-center">Inventario CEDIS</th>
                    <th class="text-center">Pedidos Pendientes(TDA + CEDIS)</th>
                    <th class="text-center">Estatus Material</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var reporte in (ViewBag.reportes))
                {
                    <tr>
                        <td class="text-center">@reporte.NumeroProveedor</td>
                        <td class="text-center">@reporte.NombreProveedor</td>
                        <td class="text-center">@reporte.Material</td>
                        <td class="text-center">@reporte.NombreMaterial</td>
                        <td class="text-center">@reporte.FechaProceso.ToString("dd/MM/yyyy")</td>
                        <td class="text-center">@reporte.UnidadMedida</td>
                        <td class="text-center">@reporte.CantidadVentas2</td>
                        <td class="text-center">@reporte.CantidadVentas1</td>
                        <td class="text-center">@reporte.CantidadVentas</td>
                        <td class="text-center">@reporte.CantidadTotal</td>
                        <td class="text-center">@reporte.CalculoTotal</td>
                        <td class="text-center">@reporte.InvTienda</td>
                        <td class="text-center">@reporte.InvTransito</td>
                        <td class="text-center">@reporte.InvCedis</td>
                        <td class="text-center">@reporte.PedidosPendiente</td>
                        <td class="text-center">@reporte.EstadoMaterial</td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>
@section Scripts {
    <script type="text/javascript">

        $(document).ready(function () {


            $('#reporteDetalle').DataTable({
                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/1.10.13/i18n/Spanish.json"
                },
                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Todos"]]
            });
        });


    </script>
}